# --------------------------------------------------
# Site settings
title: Colowrap
company: Colowrap
description: ColoWrap delivers adjustable, targeted compression to reduce looping and enhance bowel stability during colonoscopy.
email: josh@quartzstudio.com
# --------------------------------------------------
# the subpath of your site, e.g. /blog/
# baseurl: "http://colowrap.com/"
# permalink: /blog/:year/:month/:title
# paginate: 5
# paginate_path: /blog/page/:num
# --------------------------------------------------
# the base hostname & protocol for your site
# url: ""
# --------------------------------------------------
# Build settings
markdown: redcarpet
sass:
  style: compressed
# --------------------------------------------------
# Build settings
defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
